name: Create and publish a Docker image

on:
  push:
    branches: ['master']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gcc: ['8', '9', '10', '11', '12', '13', 'latest']
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Tag
        id: tag
        shell: bash
        run: |
          IMAGE=${{ env.IMAGE_NAME }}
          IMAGE=${IMAGE,,}
          if [ "${{ matrix.gcc }}" == "latest" ]; then
            TAG=${{ matrix.gcc }}
          else
            TAG=gcc-${{ matrix.gcc }}
          fi
          IMAGE_TAG="${{ env.REGISTRY }}/$IMAGE:$TAG"
          echo "$IMAGE_TAG"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}
          build-args: GCC_VERSION=${{ matrix.gcc }}
